name = "srg154"
defaultTargets = ["Srg154"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "021ce68bf125a049beee22b3fc7664d78728e21d"

[[lean_lib]]
name = "Srg154"

[leanOptions]
autoImplicit = false
